# Generated by Django 4.2.6 on 2023-10-29 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_bookcovers_book_cover_img_alter_book_type_cover'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookCovers',
            new_name='BookCover',
        ),
    ]
